#!/bin/sh
rsync -av --exclude 'lad-u' /Users/user/ladvien.github.io/_site/* root@ladvien.com:/usr/share/nginx/html

cd /Users/user/ladvien.github.io/
git add .
echo 'Enter the commit message:'
git commit -m "Blogging"
git push
