#!/bin/sh

#PASSWORD="$(keyring get system ladvien.com)"

echo ""
echo "*******************************************************"
echo "* Syncing files to Ladvien.com Jekyll build directory *"
echo "*******************************************************"
bundle exec jekyll build --source /home/ladvien/ladvien.github.io --destination /home/ladvien/ladvien.github.io/_site

echo ""
echo "*******************************************************"
echo "* Moving raw_images into images                       *"
echo "*******************************************************"
rsync -h -v -r -P -t --ignore-existing /home/ladvien/ladvien.github.io/raw_images/* /home/ladvien/ladvien.github.io/images


echo ""
echo "******************************"
echo "* Updating Website           *"
echo "******************************"
rsync -h -v -r -P -t  /home/ladvien/ladvien.github.io/_site/* root@ladvien.com:/usr/share/nginx/html
# rsync -avzu /home/ladvien/ladvien.github.io/_site/* root@ladvien.com:/usr/share/nginx/html
#rsync -avzu --ignore-existing /home/ladvien/ladvien.github.io/raw_images/* root@ladvien.com:/usr/share/nginx/html/raw_images

cd /home/ladvien/ladvien.github.io
git add .
echo ""
echo "****************************"
echo '* Enter the commit message *'
echo "****************************"
git commit -m "Blogging $(date +%Y-%m-%d)"
git push
echo ""
echo "**************************"
echo "* Sending to Ladvien.com *"
echo "**************************"
