#!/bin/sh

PASSWORD=("$(keyring get system ladvien.com)")

ECHO ""
ECHO "*******************************************************"
ECHO "* Syncing files to Ladvien.com Jekyll build directory *"
ECHO "*******************************************************"
bundle exec jekyll build --source /Users/user/Documents/GitHub/ladvien.github.io --destination /Users/user/Documents/GitHub/ladvien.github.io/_site
ECHO ""
ECHO "****************************"
ECHO "* Updating Jekyll includes *"
ECHO "****************************"

sshpass -p "$PASSWORD" rsync -avzu /Users/user/Documents/GitHub/ladvien.github.io/_site/* root@ladvien.com:/usr/share/nginx/html

cd /Users/user/Documents/GitHub/ladvien.github.io
git add .
ECHO ""
ECHO "****************************"
echo '* Enter the commit message *'
ECHO "****************************"
git commit -m "Blogging $(date +%Y-%m-%d)"
git push
ECHO ""
ECHO "**************************"
ECHO "* Sending to Ladvien.com *"
ECHO "**************************"
