#!/bin/sh

PASSWORD=("$(keyring get system ladvien.com)")
echo "$PASSWORD"
ECHO ""
ECHO "*******************************************************"
ECHO "* Syncing files to Ladvien.com Jekyll build directory *"
ECHO "*******************************************************"
bundle exec jekyll build --source /Users/caseybrittain/ladvien.github.io --destination /Users/caseybrittain/ladvien.github.io/_site

ECHO ""
ECHO "*******************************************************"
ECHO "* Moving raw_images into images                       *"
ECHO "*******************************************************"
rsync -h -v -r -P -t --ignore-existing /Users/caseybrittain/ladvien.github.io/raw_images/* /Users/caseybrittain/ladvien.github.io/images
# sips -Z 1080 /Users/caseybrittain/Documents/ladvien.github.io/images/*.jpg
# sips -Z 1080 /Users/caseybrittain/Documents/ladvien.github.io/images/*.png
# sips -Z 1080 /Users/caseybrittain/Documents/ladvien.github.io/images/*.PNG
# sips -Z 1080 /Users/caseybrittain/Documents/ladvien.github.io/images/*.JPG

ECHO ""
ECHO "****************************"
ECHO "* Updating Jekyll includes *"
ECHO "****************************"

sshpass -p "$PASSWORD" rsync -avzu /Users/caseybrittain/ladvien.github.io/_site/* root@ladvien.com:/usr/share/nginx/html


cd /Users/caseybrittain/ladvien.github.io
git add .
ECHO ""
ECHO "****************************"
echo '* Enter the commit message *'
ECHO "****************************"
git commit -m "Blogging $(date +%Y-%m-%d)"
git push
ECHO ""
ECHO "**************************"
ECHO "* Sending to Ladvien.com *"
ECHO "**************************"
