#!/bin/sh

PASSWORD=("$(keyring get system ladvien.com)")

ECHO ""
ECHO "*******************************************************"
ECHO "* Syncing files to Ladvien.com Jekyll build directory *"
ECHO "*******************************************************"
bundle exec jekyll build --source /Users/cthomasbrittain/Documents/ladvien.github.io --destination /Users/cthomasbrittain/Documents/ladvien.github.io/_site
ECHO ""
ECHO "*******************************************************"
ECHO "* Optimizing images                                   *"
ECHO "*******************************************************"
rsync -au /Users/cthomasbrittain/Documents/ladvien.github.io/images/* /Users/cthomasbrittain/Documents/ladvien.github.io/images
# sips -Z 1080 /Users/cthomasbrittain/Documents/ladvien.github.io/images/*.jpg
# sips -Z 1080 /Users/cthomasbrittain/Documents/ladvien.github.io/images/*.png
# sips -Z 1080 /Users/cthomasbrittain/Documents/ladvien.github.io/images/*.PNG
# sips -Z 1080 /Users/cthomasbrittain/Documents/ladvien.github.io/images/*.JPG

ECHO ""
ECHO "****************************"
ECHO "* Updating Jekyll includes *"
ECHO "****************************"

sshpass -p "$PASSWORD" rsync -avzu /Users/cthomasbrittain/Documents/ladvien.github.io/_site/* root@ladvien.com:/usr/share/nginx/html


cd /Users/cthomasbrittain/Documents/ladvien.github.io
git add .
ECHO ""
ECHO "****************************"
echo '* Enter the commit message *'
ECHO "****************************"
git commit -m "Blogging $(date +%Y-%m-%d)"
git push
ECHO ""
ECHO "**************************"
ECHO "* Sending to Ladvien.com *"
ECHO "**************************"
