#!/bin/sh
rsync -avz /Users/user/Dropbox/js-practice/js-ble/*.js /Users/user/ladvien.github.io/javascripts/
rsync -avz /Users/user/Dropbox/js-practice/js-ble/*.css /Users/user/ladvien.github.io/css/
rsync -avz /Users/user/Dropbox/js-practice/js-ble/*.html /Users/user/ladvien.github.io/_includes/snippets/js-ble

rsync -avz /Users/user/Dropbox/js-practice/js-ble/* /Users/user/ladvien.github.io/_includes/snippets/js-ble/

cd /Users/user/Dropbox/js-practice/js-ble
git add .
echo 'Enter the commit message:'
read commitMessage
git commit -m "$commitMessage"
git push
